### ISSUE TITLE
LinkItemCollection showing [Object, object]

### ISSUE THREAD

**Issue by whoisyourvladie** [episerver/Foundation#876]
MenuItemBlock showing [Object object] instead of link names

There are traces that there was an attempt to fix it:

-  a dojo file  ~\src\Foundation\modules\_protected\Foundation\Scripts\MenuChildItems.js that tries to fix it.
- Attribute [ClientEditor(ClientEditingClass = "foundation/MenuChildItems")] over the ChildItems property in ~\src\Foundation\Features\Blocks\MenuItemBlock\MenuItemBlock.cs **(commented out)** 

If you uncomment the attribute  - the block won't open for editing and you get an error in browser console:

`Uncaught Error: declare: mixin #0 is not a callable constructor.
    at err (dojo.js:3999:32)
    at c3mro (dojo.js:4012:5)
    at declare (dojo.js:4732:12)
    at MenuChildItems.js:15:16
    at runFactory (dojo.js:1107:43)
    at execModule (dojo.js:1236:5)
    at dojo.js:1271:6
    at guardCheckComplete (dojo.js:1251:5)
    at checkComplete (dojo.js:1266:4)
    at onLoadCallback (dojo.js:1428:7)`

**To Reproduce**
1. Login to CMS Admin
2. Open Demo Settings Import page
3. In Top Content Area find Layout Settings block
4. Edit Layout Settings block
5. Go to Menu Tab
6. In Main Menu content Area try to edit the first block
7. Scroll to bottom and observe [Object object] in Child links column of Child Items section
8. Uncomment in the source code attribute [ClientEditor(ClientEditingClass = "foundation/MenuChildItems")] over the ChildItems property in ~\src\Foundation\Features\Blocks\MenuItemBlock\MenuItemBlock.cs 
9. Restart the project, open browser dev tools and repeat steps 1-6
10.Observe the error in dev tools console

**Note**
Use main branch

**Comment by clintcfavor** [comment]
Hi, do you have an update on this?
