### ISSUE TITLE
Could not find stored procedure 'FoundationConfiguration_List'.

### ISSUE THREAD

**Issue by ashishgururani1** [episerver/Foundation#881]
Got a fresh copy today, set the path to empty database(s) in appsettings.config, builds fine, but  it comes up with the following error at runtime. 

```
Microsoft.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Could not find stored procedure 'FoundationConfiguration_List'.
  Source=Core Microsoft SqlClient Data Provider
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at Foundation.Infrastructure.Commerce.Install.InstallService.GetFoundationConfiguration() in C:\Users\testuser\Documents\GitHub\Epi12Foundation\src\Foundation\Infrastructure\Commerce\Install\InstallService.cs:line 108
   at Foundation.Infrastructure.Commerce.Install.InstallService.get_FoundationConfiguration() in C:\Users\testuser\Documents\GitHub\Epi12Foundation\src\Foundation\Infrastructure\Commerce\Install\InstallService.cs:line 36
   at Foundation.Infrastructure.Commerce.Install.InstallService.ShouldInstall() in C:\Users\testuser\Documents\GitHub\Epi12Foundation\src\Foundation\Infrastructure\Commerce\Install\InstallService.cs:line 72
   at Foundation.Infrastructure.Commerce.Extensions.InitializationEngineExtensions.InitializeFoundationCommerce(InitializationEngine context) in C:\Users\testuser\Documents\GitHub\Epi12Foundation\src\Foundation\Infrastructure\Commerce\Extensions\InitializationEngineExtensions.cs:line 26
   at Foundation.Infrastructure.InitializeSite.Initialize(InitializationEngine context) in C:\Users\testuser\Documents\GitHub\Epi12Foundation\src\Foundation\Infrastructure\InitializeSite.cs:line 177
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
```

EDIT: Wanted to add that there are hundreds of stored procedures created in the empty database as part of the startup script but there no stored procedures that start with "Foundation".

**Comment by daniel-isaacs** [comment]
> set the path to empty database(s) in appsettings.config

I think this is the problem -- if you run the setup without changing the database paths, the DB (and those connection strings) should automatically get set up, and the stored procedure should get added to the DB via [this](https://github.com/episerver/Foundation/blob/main/build/SqlScripts/FoundationConfigurationSchema.sql) (which gets run via the build script [here](https://github.com/episerver/Foundation/blob/main/setup.cmd#L127)).

Give that a shot, and let me know if it solves this issue.

**Comment by ashishgururani1** [comment]
hmm.. the app does not know where the database server is. All I am doing is 1. changing the . to a valid sql server and 2. creating empty Foundation5.Cms and Foundation5.Commerce databases. Then when I first load the app/webpage, it automatically creates the schema (tables, stored procedures, etc) but for some reason not the FoundationConfiguration_List. This process is obviously working since all that schema is being created on the first load. When you say "run the setup without changing the database paths", what do you mean exactly? 

`"ConnectionStrings": {
    "EPiServerDB": "Server=.;Database=Foundation5.Cms;User Id=Foundation5.CmsUser;Password=r@QP65dDM%mqH@^R@Lv6iBICf;TrustServerCertificate=True",
    "EcfSqlConnection": "Server=.;Database=Foundation5.Commerce;User Id=Foundation5.CmsUser;Password=r@QP65dDM%mqH@^R@Lv6iBICf;TrustServerCertificate=True"
  },`

**Comment by ashishgururani1** [comment]
I think I may need to install a sql server locally to run the setup.cmd locally. Then take that database and move to azure. Was hoping to avoid that middle work but I guess there is no way around it?

**Comment by ashishgururani1** [comment]
ok, I solved it by pre-creating the database using setup.cmd and then using that. Now to the next error.
